controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

search_patient:
    path: /patients/search
    controller: App\Controller\PatientsController::search
